In [3]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/mukhammad-irmatov/health_dataset/main/healt_info.csv")
df.head(3)

,Sno,AGE,SEX,CASTE_NAME,CATEGORY_CODE,CATEGORY_NAME,SURGERY_CODE,SURGERY,VILLAGE,MANDAL_NAME,...,CLAIM_DATE,CLAIM_AMOUNT,HOSP_NAME,HOSP_TYPE,HOSP_DISTRICT,SURGERY_DATE,DISCHARGE_DATE,Mortality Y / N,MORTALITY_DATE,SRC_REGISTRATION
0,1,56,Female,BC,M6,NEPHROLOGY,M6.5,Maintenance Hemodialysis For Crf,Lolugu,Ponduru,...,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,Srikakulam,06-08-2013 00:00,07-09-2013 00:00,NO,NaN,D
1,2,37,Male,BC,M6,NEPHROLOGY,M6.5,Maintenance Hemodialysis For Crf,Borivanka,Kaviti,...,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,Srikakulam,08-08-2013 00:00,09-09-2013 00:00,NO,NaN,D
2,3,50,Male,BC,M6,NEPHROLOGY,M6.5,Maintenance Hemodialysis For Crf,Kapasakuddi,Kaviti,...,22-03-2017 20:25,11500,"Rims Govt. General Hospital, Srikakulam",G,Srikakulam,15-08-2013 00:00,18-10-2013 00:00,NO,NaN,D

In [8]:
df.duplicated().sum()

0

In [14]:
df.drop(['Sno', 'CATEGORY_CODE', 'SURGERY_CODE', 'MANDAL_NAME', 'DISTRICT_NAME', 'HOSP_DISTRICT'], axis=1, inplace=True)

In [15]:
df

,AGE,SEX,CASTE_NAME,CATEGORY_NAME,SURGERY,VILLAGE,PREAUTH_DATE,PREAUTH_AMT,CLAIM_DATE,CLAIM_AMOUNT,HOSP_NAME,HOSP_TYPE,SURGERY_DATE,DISCHARGE_DATE,Mortality Y / N,MORTALITY_DATE,SRC_REGISTRATION
0,56,Female,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Lolugu,03-08-2013 20:38,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,06-08-2013 00:00,07-09-2013 00:00,NO,NaN,D
1,37,Male,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Borivanka,06-08-2013 07:26,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,08-08-2013 00:00,09-09-2013 00:00,NO,NaN,D
2,50,Male,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Kapasakuddi,09-08-2013 18:30,12500,22-03-2017 20:25,11500,"Rims Govt. General Hospital, Srikakulam",G,15-08-2013 00:00,18-10-2013 00:00,NO,NaN,D
3,45,Male,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Telikipenta,24-08-2013 19:37,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,24-08-2013 00:00,27-09-2013 00:00,NO,NaN,D
4,54,Male,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Thandemvalasa,28-08-2013 17:03,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,31-08-2013 00:00,02-10-2013 00:00,NO,NaN,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335389,65,Male,SC,OPHTHALMOLOGY SURGERY,Vitrectomy Plus Silicon Oil Or Gas (14.75),Chintalapudi,08-06-2017 06:40,23320,04-08-2017 21:23,23320,Sankar Eye Hospital,C,09-06-2017 00:00,10-06-2017 00:00,NO,NaN,D
335390,54,Female,OC,MEDICAL ONCOLOGY,Chemotherapy for Breast Cancer with Paclitaxel,Udayagiri @ Kondayapale,05-06-2017 22:35,7140,02-08-2017 19:11,7140,BASAVATARAKAM INDO AMERICAN CANCER HOSPITAL an...,C,06-06-2017 00:00,06-06-2017 00:00,NO,NaN,D
335391,19,Female,SC,MEDICAL ONCOLOGY,Palliative Chemotherapy for unlisted Regimen,Vinduru,06-06-2017 06:13,5000,04-10-2017 19:46,5000,M.N.J.Hospitals,G,09-06-2017 00:00,10-06-2017 00:00,NO,NaN,D
335392,50,Male,BC,GENITO URINARY SURGERIES,ursl,Duppituru,05-06-2017 23:37,25000,04-08-2017 20:59,25000,GAJUWAKA HOSPITALS PVT LTD RK HOSPITAL,C,06-06-2017 00:00,10-06-2017 00:00,NO,NaN,D
335393,46,Female,SC,MEDICAL ONCOLOGY,Chemotherapy for Cervical Cancer with Weekly C...,Ananthavaram,06-06-2017 23:02,2040,09-08-2017 19:43,2040,SURYA GLOBAL MULTI SPECIALITY HOSPITALS AND CA...,C,07-06-2017 00:00,07-06-2017 00:00,NO,NaN,MC

In [16]:
df["SEX"].unique()

array(['Female', 'Male', 'Male(Child)', 'Female(Child)', 'FEMALE'],
      dtype=object)

In [17]:
dict = {"Male":"Erkak","Male(child)":"Erkak", "Female":"Ayol","Female(child)":"Ayol","MALE":"Erkak","FEMALE":"Ayol"}
df["SEX"] = df["SEX"].map(dict)

In [20]:
dict2 = {'Erkak':1, 'Ayol':0}
df["SEX"] = df["SEX"].map(dict2)
df.head(5)

,AGE,SEX,CASTE_NAME,CATEGORY_NAME,SURGERY,VILLAGE,PREAUTH_DATE,PREAUTH_AMT,CLAIM_DATE,CLAIM_AMOUNT,HOSP_NAME,HOSP_TYPE,SURGERY_DATE,DISCHARGE_DATE,Mortality Y / N,MORTALITY_DATE,SRC_REGISTRATION
0,56,NaN,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Lolugu,03-08-2013 20:38,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,06-08-2013 00:00,07-09-2013 00:00,NO,NaN,D
1,37,NaN,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Borivanka,06-08-2013 07:26,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,08-08-2013 00:00,09-09-2013 00:00,NO,NaN,D
2,50,NaN,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Kapasakuddi,09-08-2013 18:30,12500,22-03-2017 20:25,11500,"Rims Govt. General Hospital, Srikakulam",G,15-08-2013 00:00,18-10-2013 00:00,NO,NaN,D
3,45,NaN,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Telikipenta,24-08-2013 19:37,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,24-08-2013 00:00,27-09-2013 00:00,NO,NaN,D
4,54,NaN,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Thandemvalasa,28-08-2013 17:03,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",G,31-08-2013 00:00,02-10-2013 00:00,NO,NaN,D

In [21]:

df["HOSP_TYPE"] = df["HOSP_TYPE"].map({'G':"Umumiy", 'C':"Maxsus"})

In [22]:
df

,AGE,SEX,CASTE_NAME,CATEGORY_NAME,SURGERY,VILLAGE,PREAUTH_DATE,PREAUTH_AMT,CLAIM_DATE,CLAIM_AMOUNT,HOSP_NAME,HOSP_TYPE,SURGERY_DATE,DISCHARGE_DATE,Mortality Y / N,MORTALITY_DATE,SRC_REGISTRATION
0,56,NaN,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Lolugu,03-08-2013 20:38,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",Umumiy,06-08-2013 00:00,07-09-2013 00:00,NO,NaN,D
1,37,NaN,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Borivanka,06-08-2013 07:26,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",Umumiy,08-08-2013 00:00,09-09-2013 00:00,NO,NaN,D
2,50,NaN,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Kapasakuddi,09-08-2013 18:30,12500,22-03-2017 20:25,11500,"Rims Govt. General Hospital, Srikakulam",Umumiy,15-08-2013 00:00,18-10-2013 00:00,NO,NaN,D
3,45,NaN,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Telikipenta,24-08-2013 19:37,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",Umumiy,24-08-2013 00:00,27-09-2013 00:00,NO,NaN,D
4,54,NaN,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Thandemvalasa,28-08-2013 17:03,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",Umumiy,31-08-2013 00:00,02-10-2013 00:00,NO,NaN,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335389,65,NaN,SC,OPHTHALMOLOGY SURGERY,Vitrectomy Plus Silicon Oil Or Gas (14.75),Chintalapudi,08-06-2017 06:40,23320,04-08-2017 21:23,23320,Sankar Eye Hospital,Maxsus,09-06-2017 00:00,10-06-2017 00:00,NO,NaN,D
335390,54,NaN,OC,MEDICAL ONCOLOGY,Chemotherapy for Breast Cancer with Paclitaxel,Udayagiri @ Kondayapale,05-06-2017 22:35,7140,02-08-2017 19:11,7140,BASAVATARAKAM INDO AMERICAN CANCER HOSPITAL an...,Maxsus,06-06-2017 00:00,06-06-2017 00:00,NO,NaN,D
335391,19,NaN,SC,MEDICAL ONCOLOGY,Palliative Chemotherapy for unlisted Regimen,Vinduru,06-06-2017 06:13,5000,04-10-2017 19:46,5000,M.N.J.Hospitals,Umumiy,09-06-2017 00:00,10-06-2017 00:00,NO,NaN,D
335392,50,NaN,BC,GENITO URINARY SURGERIES,ursl,Duppituru,05-06-2017 23:37,25000,04-08-2017 20:59,25000,GAJUWAKA HOSPITALS PVT LTD RK HOSPITAL,Maxsus,06-06-2017 00:00,10-06-2017 00:00,NO,NaN,D
335393,46,NaN,SC,MEDICAL ONCOLOGY,Chemotherapy for Cervical Cancer with Weekly C...,Ananthavaram,06-06-2017 23:02,2040,09-08-2017 19:43,2040,SURYA GLOBAL MULTI SPECIALITY HOSPITALS AND CA...,Maxsus,07-06-2017 00:00,07-06-2017 00:00,NO,NaN,MC

In [23]:
df['HOSP_TYPE'].value_counts()

Maxsus    241139
Umumiy     94255
Name: HOSP_TYPE, dtype: int64

In [24]:
sum(df.duplicated())

32

In [25]:
df.drop_duplicates(inplace=True)

In [26]:
df

,AGE,SEX,CASTE_NAME,CATEGORY_NAME,SURGERY,VILLAGE,PREAUTH_DATE,PREAUTH_AMT,CLAIM_DATE,CLAIM_AMOUNT,HOSP_NAME,HOSP_TYPE,SURGERY_DATE,DISCHARGE_DATE,Mortality Y / N,MORTALITY_DATE,SRC_REGISTRATION
0,56,NaN,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Lolugu,03-08-2013 20:38,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",Umumiy,06-08-2013 00:00,07-09-2013 00:00,NO,NaN,D
1,37,NaN,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Borivanka,06-08-2013 07:26,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",Umumiy,08-08-2013 00:00,09-09-2013 00:00,NO,NaN,D
2,50,NaN,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Kapasakuddi,09-08-2013 18:30,12500,22-03-2017 20:25,11500,"Rims Govt. General Hospital, Srikakulam",Umumiy,15-08-2013 00:00,18-10-2013 00:00,NO,NaN,D
3,45,NaN,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Telikipenta,24-08-2013 19:37,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",Umumiy,24-08-2013 00:00,27-09-2013 00:00,NO,NaN,D
4,54,NaN,BC,NEPHROLOGY,Maintenance Hemodialysis For Crf,Thandemvalasa,28-08-2013 17:03,12500,22-03-2017 20:25,11000,"Rims Govt. General Hospital, Srikakulam",Umumiy,31-08-2013 00:00,02-10-2013 00:00,NO,NaN,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335389,65,NaN,SC,OPHTHALMOLOGY SURGERY,Vitrectomy Plus Silicon Oil Or Gas (14.75),Chintalapudi,08-06-2017 06:40,23320,04-08-2017 21:23,23320,Sankar Eye Hospital,Maxsus,09-06-2017 00:00,10-06-2017 00:00,NO,NaN,D
335390,54,NaN,OC,MEDICAL ONCOLOGY,Chemotherapy for Breast Cancer with Paclitaxel,Udayagiri @ Kondayapale,05-06-2017 22:35,7140,02-08-2017 19:11,7140,BASAVATARAKAM INDO AMERICAN CANCER HOSPITAL an...,Maxsus,06-06-2017 00:00,06-06-2017 00:00,NO,NaN,D
335391,19,NaN,SC,MEDICAL ONCOLOGY,Palliative Chemotherapy for unlisted Regimen,Vinduru,06-06-2017 06:13,5000,04-10-2017 19:46,5000,M.N.J.Hospitals,Umumiy,09-06-2017 00:00,10-06-2017 00:00,NO,NaN,D
335392,50,NaN,BC,GENITO URINARY SURGERIES,ursl,Duppituru,05-06-2017 23:37,25000,04-08-2017 20:59,25000,GAJUWAKA HOSPITALS PVT LTD RK HOSPITAL,Maxsus,06-06-2017 00:00,10-06-2017 00:00,NO,NaN,D
335393,46,NaN,SC,MEDICAL ONCOLOGY,Chemotherapy for Cervical Cancer with Weekly C...,Ananthavaram,06-06-2017 23:02,2040,09-08-2017 19:43,2040,SURYA GLOBAL MULTI SPECIALITY HOSPITALS AND CA...,Maxsus,07-06-2017 00:00,07-06-2017 00:00,NO,NaN,MC